### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by karanmartian** [unlayer/react-email-editor#23] opened 2018-06-07 11:32 UTC
I am opening this issue because this is still not working with me on React 16. The exact same code was working fine on React 15. I am on 

"react": "^16.3.2"
"react-dom": "^16.3.2",
"react-email-editor": "^0.8.1",

and i keep getting this error even with the sample README code:
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by umairsiddique** [comment] 2018-06-09 00:11
Duplicate of #14

**Closed by umairsiddique** 2018-06-09 00:11 UTC
