### ISSUE TITLE
Discrepancy between editor & exported HTML for paragraphs

### ISSUE THREAD

**Issue by felipehertzer** [unlayer/react-email-editor#326] opened 2023-03-24 03:34 UTC
Hi,

I'm having a problem with space between paragraphs in the editor. The editor is showing the texts less spaced than when viewing the generated html

Editor:
![Image 2](https://i.imgur.com/mBP2SJ6.png)

Exported HTML:
![Image](https://i.imgur.com/OPZflcZ.png)

In the Unlayer CSS code, I can see that the classes are setting the paragraph margin to zero, but when exported, this margin is not exported. Is it possible to remove these classes from the editor or add this margin when exporting the HTML?
```css
.design-web p {
    margin: 0;
}
p {
    margin: 0;
}
```

Thank you.

**Comment by andreas-globi** [comment] 2023-04-14 11:43
I'm having the same issue. Seems to be a recent development. This is annoying a LOT of our users.

Would someone PLEASE put in a fix for this so that the editor more closely represents the output?

**Comment by brunolemos** [comment] 2023-06-19 20:56
Back in the day, this was caused by a Chrome update (version 112). This has been fixed on Unlayer side a couple months ago, so I'm closing this. If you are still facing this issue with the latest version please let us know.

**Closed by brunolemos** 2023-06-19 20:56 UTC

**Comment by felipehertzer** [comment] 2024-01-24 05:37
Hey @brunolemos, sorry to bump this up again, but the problem started again, the lines are close together again, different from the output due to this css:

```css
.design-web p {
    margin: 0;
}
```
