### ISSUE TITLE
gaps between paragraphs

### ISSUE THREAD

**Issue by andreas-globi** [unlayer/react-email-editor#333] opened 2023-04-14 12:03 UTC
The editor is (of late) injecting gaps between paragraphs.

This seems related to [issue 326](https://github.com/unlayer/react-email-editor/issues/326)

We have many old templates that export fine, and the editor view matches the output. 

After saving the template again (with zero edits), the output suddenly has gaps between all paragraphs, which is effectively messing up all existing users' templates when they make the smallest change.

**Comment by brunolemos** [comment] 2023-06-19 20:57
Closing as duplicate of #326. 

Back in the day, this was caused by a Chrome update (version 112). This has been fixed on Unlayer side a couple months ago, so I'm closing this. If you are still facing this issue with the latest version please let us know.

**Closed by brunolemos** 2023-06-19 20:57 UTC
